#---------------------------------------------------
#General Parameters 
#---------------------------------------------------
ALL: "Zebrafishes"
SAMPLES: "samples.tsv"
nCount1: 1200
nCount2: 30000
nfeatures1: 800
nfeatures2: 6000
mt: 25


